[build-system]
requires = [
    "setuptools >= 54.2.0",
    "setuptools_scm >= 2.0.0, <3",
    "cython >= 0.29.23",
    "numpy",
    "scipy"
]

build-backend = "setuptools.build_meta"

[project]
name = "Sella"
version = "2.3.5"
requires-python = ">=3.8"
readme = "README.md"
dependencies = [
    "numpy>=1.14.0",
    "scipy>=1.1.0",
    "ase>=3.18.0",
    "jax>=0.4.20",
    "jaxlib>=0.4.20",
    "numba>=0.57.0",
]

[project.optional-dependencies]
test = [
    "pytest",
    "cython >= 0.29.23",
]

[tool.cibuildwheel]
skip = [
    # skip pypy
    "pp*",
    # skip 32-bit archs
    "*-win32",
    "*-manylinux_i686",
    # skip musllinux
    "*-musllinux*",
]
